# Generated by Django 5.2.1 on 2025-05-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coupon_methodelivraison_adresselivraison_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='methode_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.methodelivraison', verbose_name='Méthode de livraison'),
        ),
    ]
